version: '3'

services:
  pgdb_weaver:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - ./cli_tools/postgis-data:/var/lib/postgresql
      - ./cli_tools/:/backups
    container_name: pgdb_weav_container
    environment:
      - POSTGRES_DB=testdb_weaver
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=Password12!
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure

  weav:
    container_name: weaver_container
    image: weaver_image
    command: bash -c "Python --version"
    environment:
      # Handle tzdata install see: https://serverfault.com/a/975084
      TZ: America/New_York
      DEBIAN_FRONTEND: noninteractive
      # If IN_DOCKER is set, use service names as hosts names(travis)
      # otherwise use localhost (local tests)
      "IN_DOCKER" : "true"
      "PGUSER" : "postgres"
      "PGPASSWORD" : "Password12!"
      "PGDATABASE" : "testdb_weaver"
      "PGPORT" : "5432"
      "PGHOST" : "pgdb_weaver"
    restart: on-failure
    build: .

    depends_on:
      - pgdb_weaver

    ports:
      - 5001:80
